# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matrix.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'matrix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\x06matrix\"\xa2\x01\n\x15MatrixMultiplyRequest\x12\x10\n\x08matrix_a\x18\x01 \x01(\x0c\x12\x0e\n\x06rows_a\x18\x02 \x01(\x05\x12\x0e\n\x06\x63ols_a\x18\x03 \x01(\x05\x12\x10\n\x08matrix_b\x18\x04 \x01(\x0c\x12\x0e\n\x06rows_b\x18\x05 \x01(\x05\x12\x0e\n\x06\x63ols_b\x18\x06 \x01(\x05\x12\x11\n\tnum_cores\x18\x07 \x01(\x05\x12\x12\n\nblock_size\x18\x08 \x01(\x05\"D\n\x16MatrixMultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x05\x32Z\n\rMatrixService\x12I\n\x08Multiply\x12\x1d.matrix.MatrixMultiplyRequest\x1a\x1e.matrix.MatrixMultiplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATRIXMULTIPLYREQUEST']._serialized_start=25
  _globals['_MATRIXMULTIPLYREQUEST']._serialized_end=187
  _globals['_MATRIXMULTIPLYRESPONSE']._serialized_start=189
  _globals['_MATRIXMULTIPLYRESPONSE']._serialized_end=257
  _globals['_MATRIXSERVICE']._serialized_start=259
  _globals['_MATRIXSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
